# Data Pipeline for Senate LDA Expenses
---

This is a data pipe designed to be used to pull out and sum all Senate LDA expense data while removing duplicates created by amendments or double-filling. The data at the end is very similar to Open secrets data, though the Open Secrets lobbying page shows totals that include the income statements from lobbying firms and I don't know much about those so I've left them out to be added at some future date. 

## Input Requirements
- To run this pipeline you will need to first get a csv from lobbyfinder.py
- This pipeline is designed to use all of the inbuild column names from lobbyfinder.py so I don't think it will work with anything else

## To Use
- Make sure all requirements are installed, as I installed the ones I needed as I went
- import your .csv into this folder and change the pdf.readcsv to your .csv name


## Output
- This will leave you with 4 graphics in the Viz folder all built with ploty so that you can interact with them in the notebook to check values and dates. 

### Libraries Used
- pandas, plotly, kaledio, nbformat

### DataFrames in this Pipeline

| DataFrame | Created From | Purpose |
|---|---|---|
| `df` | CSV file | Raw data — untouched source |
| `df_clean` | `df` | Filtered to `role == 'registrant'` only |
| `dupes` | `df_clean` | Diagnostic view — shows quarters with more than one filing |
| `df_deduped` | `df_clean` | Primary clean df — duplicates removed, keeping latest `dt_posted` per client/year/quarter |
| `df_yearly` | `df_deduped` | Expenses summed by company + year — feeds per-company line chart |
| `df_pct` | `df_yearly` | Adds year-over-year % change per company — feeds % change line chart |
| `df_total` | `df_deduped` | All companies

---
### Last Update: 04/26/26
---

## Step 1: dependances and importing the data

In [18]:
%pip install plotly

import sys
!{sys.executable} -m pip install kaleido

import plotly.io as pio
pio.kaleido.scope.mathjax = None

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in c:\users\craig\appdata\roaming\python\python313\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\craig\appdata\roaming\python\python313\site-packages (from plotly) (2.16.0)
Requirement already satisfied: packaging in c:\users\craig\appdata\roaming\python\python313\site-packages (from plotly) (26.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaleido in c:\users\craig\appdata\roaming\python\python313\site-packages (1.2.0)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\craig\appdata\roaming\python\python313\site-packages (from kaleido) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\craig\appdata\roaming\python\python313\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\craig\appdata\roaming\python\python313\site-packages (from kaleido) (3.11.8)
Requirement already satisfied: packaging in c:\users\craig\appdata\roaming\python\python313\site-packages (from kaleido) (26.0)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\craig\appdata\roaming\python\python313\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\craig\appdata\roaming\python\python313\site-packages (from choreographer>=1.1.1->kaleido) (4.1.1)
Requirement already satisfied: pytest>=7.0.0 in c:\users\craig\appdata\roaming\python\python313\site-packages (from pytest-timeout>=2.4.0->kaleido) (9.0.3)
Requirement already satisfied: colorama>=0.4 in c:\users\craig\appdata\roaming\python\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\craig\appdata\roaming\python\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\craig\appdata\roaming\python\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\craig\appdata\roaming\python\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
C:\Users\craig\AppData\Local\Temp\ipykernel_26156\1501935392.py:7: DeprecationWarning:
Use of plotly.io.kaleido.scope.mathjax is deprecated and support will be removed after September 2025.
Please use plotly.io.defaults.mathjax instead.

  pio.kaleido.scope.mathjax = None

In [19]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [20]:
df = pd.read_csv('lobbying_filings_Primes.csv')
df.head()

,source,query_company,role,filing_uuid,filing_year,period,filing_type,dt_posted,registrant_name,registrant_id,client_name,client_id,income,expenses,lobbying_issues,url
0,Senate LDA,Lockheed,client,49117f1a-a236-4583-a60e-919cc59e79c4,1999,NaN,Year-End Report,2000-02-14T00:00:00-05:00,THE RHOADS GROUP,6644,LOCKHEED MARTIN CORP,108908,120000.0,NaN,Defense; Telecommunications,https://lda.senate.gov/filings/public/filing/4...
1,Senate LDA,Lockheed,client,31f28e72-7236-4837-b0b6-8d262d1d6cd8,1999,NaN,Year-End Report,2000-02-14T00:00:00-05:00,VAN SCOYOC ASSOCIATES,39837,LOCKHEED MARTIN MISSILES & SPACE CO,147700,20000.0,NaN,Defense; Budget/Appropriations,https://lda.senate.gov/filings/public/filing/3...
2,Senate LDA,Lockheed,client,5d60eeb6-241e-4977-b0d1-852a36436cbf,1999,NaN,Mid-Year Termination (No Activity),1999-08-13T00:00:00-04:00,"CARTER GROUP, LLC",49008,LOCKHEED MARTIN AIRCRAFT & LOGISTICS CENTERS,156072,NaN,NaN,NaN,https://lda.senate.gov/filings/public/filing/5...
3,Senate LDA,Lockheed,client,d52d60e0-0536-4207-8d87-9c1084e31025,1999,NaN,Year-End Report,2000-02-14T00:00:00-05:00,O'MELVENY & MYERS LLP,29904,LOCKHEED MARTIN CORP,135265,100000.0,NaN,Aerospace,https://lda.senate.gov/filings/public/filing/d...
4,Senate LDA,Lockheed,client,4e6ca9fd-7bad-451e-8a13-d7a698af4815,1999,NaN,Year-End Report,2000-02-14T00:00:00-05:00,DAP & ASSOC,48986,LOCKHEED MARTIN CORP,156067,120000.0,NaN,Telecommunications; Communications/Broadcastin...,https://lda.senate.gov/filings/public/filing/4...

## Step 2 - Data Cleaning

In [21]:
# Filter for [role] = registrant 

df_clean = df[df['role'] == 'registrant']

In [22]:
# Gather Duplicate Quarter reports & Amendments

dupes = df_clean[df_clean.duplicated(subset=['client_name', 'filing_year', 'filing_type'], keep=False)]
dupes[['client_name', 'filing_year', 'filing_type', 'dt_posted']].sort_values(['client_name', 'filing_year', 'filing_type'])

,client_name,filing_year,filing_type,dt_posted
4018,BOEING COMPANY,2000,Registration - Amendment,2000-08-11T00:00:00-04:00
4019,BOEING COMPANY,2000,Registration - Amendment,2000-11-08T00:00:00-05:00
4021,BOEING COMPANY,2000,Registration - Amendment,2001-02-14T00:00:00-05:00
4027,BOEING COMPANY,2003,Registration - Amendment,2003-02-13T00:00:00-05:00
4028,BOEING COMPANY,2003,Registration - Amendment,2003-05-21T00:00:00-04:00
4044,BOEING COMPANY,2007,Registration - Amendment,2007-03-22T11:53:25-04:00
4048,BOEING COMPANY,2007,Registration - Amendment,2008-06-08T00:00:00-04:00
3314,GENERAL DYNAMICS CORP,2005,Mid-Year Report,2005-08-12T00:00:00-04:00
3315,GENERAL DYNAMICS CORP,2005,Mid-Year Report,2006-02-14T00:00:00-05:00
3343,GENERAL DYNAMICS CORP,2013,1st Quarter - Report,2013-04-22T17:30:38.117000-04:00
3344,GENERAL DYNAMICS CORP,2013,1st Quarter - Report,2013-04-30T13:08:08.220000-04:00
3370,GENERAL DYNAMICS CORP,2019,1st Quarter - Amendment,2019-04-19T12:02:35.313000-04:00
3372,GENERAL DYNAMICS CORP,2019,1st Quarter - Amendment,2019-08-19T11:48:16.633000-04:00
1094,LOCKHEED MARTIN CORPORATION,2006,Mid-Year Amendment,2006-08-14T00:00:00-04:00
1099,LOCKHEED MARTIN CORPORATION,2006,Mid-Year Amendment,2008-02-26T16:09:44-05:00
1102,LOCKHEED MARTIN CORPORATION,2008,1st Quarter - Amendment,2008-06-03T14:07:18-04:00
1111,LOCKHEED MARTIN CORPORATION,2008,1st Quarter - Amendment,2009-09-28T12:02:59-04:00
1100,LOCKHEED MARTIN CORPORATION,2008,1st Quarter - Report,2008-04-18T14:17:05-04:00
1101,LOCKHEED MARTIN CORPORATION,2008,1st Quarter - Report,2008-04-21T11:01:36-04:00
1108,LOCKHEED MARTIN CORPORATION,2009,1st Quarter - Amendment,2009-05-05T15:27:17-04:00
1109,LOCKHEED MARTIN CORPORATION,2009,1st Quarter - Amendment,2009-07-17T14:42:49-04:00
1113,LOCKHEED MARTIN CORPORATION,2009,1st Quarter - Amendment,2009-11-03T14:28:59-05:00
1116,LOCKHEED MARTIN CORPORATION,2009,1st Quarter - Amendment,2010-04-01T16:15:48.910000-04:00
1114,LOCKHEED MARTIN CORPORATION,2009,2nd Quarter - Amendment,2009-11-03T15:25:17-05:00
1117,LOCKHEED MARTIN CORPORATION,2009,2nd Quarter - Amendment,2010-04-01T16:16:55.190000-04:00
1128,LOCKHEED MARTIN CORPORATION,2010,4th Quarter - Amendment,2011-04-29T14:10:36.577000-04:00
1135,LOCKHEED MARTIN CORPORATION,2010,4th Quarter - Amendment,2012-09-10T16:22:46.650000-04:00
1161,LOCKHEED MARTIN CORPORATION,2015,1st Quarter - Amendment,2016-09-02T12:20:34.173000-04:00
1172,LOCKHEED MARTIN CORPORATION,2015,1st Quarter - Amendment,2018-09-14T14:22:30.850000-04:00
1195,LOCKHEED MARTIN CORPORATION,2022,1st Quarter - Amendment,2022-07-20T15:48:13-04:00
1200,LOCKHEED MARTIN CORPORATION,2022,1st Quarter - Amendment,2023-09-08T16:54:23-04:00
1983,MORTGAGE BANKERS ASSOCIATION,2006,Year-End Termination,2009-07-15T00:00:00-04:00
1985,MORTGAGE BANKERS ASSOCIATION,2006,Year-End Termination,2009-10-02T00:00:00-04:00
2539,NORTHROP GRUMMAN CORPORATION,2003,Registration - Amendment,2003-08-18T00:00:00-04:00
2559,NORTHROP GRUMMAN CORPORATION,2003,Registration - Amendment,2010-08-24T08:48:21.057000-04:00
2561,NORTHROP GRUMMAN CORPORATION,2003,Registration - Amendment,2010-11-04T11:38:04.500000-04:00
2563,NORTHROP GRUMMAN CORPORATION,2003,Registration - Amendment,2011-03-22T09:01:52.273000-04:00
2566,NORTHROP GRUMMAN CORPORATION,2011,Registration - Amendment,2011-06-09T10:45:17.017000-04:00
2567,NORTHROP GRUMMAN CORPORATION,2011,Registration - Amendment,2011-06-27T12:59:24.243000-04:00
2570,NORTHROP GRUMMAN CORPORATION,2011,Registration - Amendment,2011-11-03T13:26:57.747000-04:00
2571,NORTHROP GRUMMAN CORPORATION,2011,Registration - Amendment,2011-11-11T09:22:48-05:00
2581,NORTHROP GRUMMAN CORPORATION,2013,2nd Quarter - Amendment,2013-07-19T12:45:51.840000-04:00
2586,NORTHROP GRUMMAN CORPORATION,2013,2nd Quarter - Amendment,2014-05-22T13:51:49.237000-04:00
2579,NORTHROP GRUMMAN CORPORATION,2013,2nd Quarter - Report,2013-07-19T11:55:03.333000-04:00
2580,NORTHROP GRUMMAN CORPORATION,2013,2nd Quarter - Report,2013-07-19T12:22:22.247000-04:00
1437,RTX CORPORATION AND AFFILIATES,2008,3rd Quarter - Report,2008-10-17T10:50:36-04:00
1438,RTX CORPORATION AND AFFILIATES,2008,3rd Quarter - Report,2009-01-09T12:42:32-05:00

In [23]:
# View Total year for identified dups

df_clean[(df_clean['client_name'] == 'AEROVIRONMENT INC.') & (df_clean['filing_year'] == 2009)]

Empty DataFrame
Columns: [source, query_company, role, filing_uuid, filing_year, period, filing_type, dt_posted, registrant_name, registrant_id, client_name, client_id, income, expenses, lobbying_issues, url]
Index: []

In [24]:
# Creating a new column for base_quarter, and removing dups based on dt_posted datetime

df_clean['base_quarter'] = df_clean['filing_type'].str.replace(r'\s*-\s*(Report|Amendment).*', '', regex=True).str.strip()

df_deduped = (
    df_clean.sort_values('dt_posted', ascending=False)
            .drop_duplicates(subset=['client_name', 'filing_year', 'base_quarter'], keep='first')
            .reset_index(drop=True)
)

In [25]:
df_deduped[(df_deduped['client_name'] == 'AEROVIRONMENT INC.') & (df_deduped['filing_year'] == 2010)]

Empty DataFrame
Columns: [source, query_company, role, filing_uuid, filing_year, period, filing_type, dt_posted, registrant_name, registrant_id, client_name, client_id, income, expenses, lobbying_issues, url, base_quarter]
Index: []

In [26]:
# Sum the expenses for the deduped years

df_deduped.groupby('filing_year')['expenses'].sum().reset_index().style.format({'expenses': '${:,.0f}'})

In [27]:
df_deduped.groupby(['client_name', 'filing_year'])['expenses'].sum().reset_index().style.format({'expenses': '${:,.0f}'})

## Step 3 - Vizualizations

In [28]:
# installing additional dependancies 

import sys
!{sys.executable} -m pip install --upgrade nbformat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in c:\users\craig\appdata\roaming\python\python313\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\craig\appdata\roaming\python\python313\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\craig\appdata\roaming\python\python313\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\craig\appdata\roaming\python\python313\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\craig\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\craig\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\craig\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\craig\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\craig\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\craig\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
# Graphing each companies summed expenses per year

df_yearly = df_deduped.groupby(['client_name', 'filing_year'])['expenses'].sum().reset_index()

fig = px.line(df_yearly, x='filing_year', y='expenses', color='client_name', markers=True,
              labels={'filing_year': 'Year', 'expenses': 'Lobbying Expenses', 'client_name': 'Company'})
fig.update_layout(hoverlabel=dict(bgcolor='white', font_color='black', bordercolor='lightgrey'))
fig.update_layout(title='Total Company Lobbying Expenses by Year')

fig.show()

fig.write_image('Viz/Company_change_expenses_by_year.svg', scale=2)

In [30]:
# creating the % change dataset

df_pct = (
    df_deduped.groupby(['client_name', 'filing_year'])['expenses'].sum()
    .reset_index()
    .sort_values(['client_name', 'filing_year'])
)

df_pct['pct_change'] = df_pct.groupby('client_name')['expenses'].pct_change() * 100
df_pct['pct_change'] = df_pct['pct_change'].fillna(0)


df_pct.head(20)

        client_name  filing_year   expenses  pct_change
0   BAE SYSTEMS INC         1999   200000.0    0.000000
1   BAE SYSTEMS INC         2000   480000.0  140.000000
2   BAE SYSTEMS INC         2001   920000.0   91.666667
3   BAE SYSTEMS INC         2002  1600000.0   73.913043
4   BAE SYSTEMS INC         2003  1620000.0    1.250000
5   BAE SYSTEMS INC         2004  1420000.0  -12.345679
6   BAE SYSTEMS INC         2005  4000000.0  181.690141
7   BAE SYSTEMS INC         2006  8420000.0  110.500000
8   BAE SYSTEMS INC         2007  4160000.0  -50.593824
9   BAE SYSTEMS INC         2008  5230000.0   25.721154
10  BAE SYSTEMS INC         2009  4670000.0  -10.707457
11  BAE SYSTEMS INC         2010  4707000.0    0.792291
12  BAE SYSTEMS INC         2011  4230000.0  -10.133843
13  BAE SYSTEMS INC         2012  4520000.0    6.855792
14  BAE SYSTEMS INC         2013  4270000.0   -5.530973
15  BAE SYSTEMS INC         2014  3630000.0  -14.988290
16  BAE SYSTEMS INC         2015  3730000.0    2.754821
17  BAE SYSTEMS INC         2016  3580000.0   -4.021448
18  BAE SYSTEMS INC         2017  3980000.0   11.173184
19  BAE SYSTEMS INC         2018  4080000.0    2.512563

In [31]:
# Graphing %change by company

fig = px.line(df_pct, x='filing_year', y='pct_change', color='client_name', markers=True,
              labels={'filing_year': 'Year', 'pct_change': '% Change in Expenses', 'client_name': 'Company'})
fig.add_hline(y=0, line_dash='dash', line_color='grey')
fig.update_layout(hoverlabel=dict(bgcolor='white', font_color='black', bordercolor='lightgrey'))
fig.update_layout(title='% Change in Lobbying Expenses by Year')

fig.write_image('Viz/%_change_expenses_by_year.svg', scale=2)

fig.show()

In [32]:
# showing totals

df_total = df_deduped.groupby('filing_year')['expenses'].sum().reset_index()
df_total['pct_change'] = df_total['expenses'].pct_change() * 100
df_total['pct_change'] = df_total['pct_change'].fillna(0)

fig1 = px.line(df_total, x='filing_year', y='expenses', markers=True,
               title='Total Lobbying Expenses by Year',
               labels={'filing_year': 'Year', 'expenses': 'Total Expenses'})
fig1.update_layout(hoverlabel=dict(bgcolor='white', font_color='black', bordercolor='lightgrey'))
fig1.show()

fig2 = px.line(df_total, x='filing_year', y='pct_change', markers=True,
               title='% Change in Total Lobbying Expenses by Year',
               labels={'filing_year': 'Year', 'pct_change': '% Change'})
fig2.add_hline(y=0, line_dash='dash', line_color='grey')
fig2.update_layout(hoverlabel=dict(bgcolor='white', font_color='black', bordercolor='lightgrey'))


fig1.write_image('Viz/total_expenses_by_year.svg', scale=2)
fig2.write_image('Viz/pct_change_total_expenses.svg', scale=2)

fig2.show()